trigger:
  batch: true
  branches:
    include:
    - main

pr:
- main

schedules:
- cron: 0 12 * * 0
  displayName: weekly Sunday build
  branches:
    include:
    - main
  always: true

parameters:

- name: operating_systems
  type: object
  default:
  - ubuntu
  # Dependencies and the corresponding CG alerts may be different
  # in each operating system.
  - windows

jobs:

- ${{ each os in parameters.operating_systems }}:

  - job: ${{ os }}

    pool:
      vmImage: ${{ image }}-latest

    steps:

    - checkout: self
      clean: true

    - pwsh: |
        Get-ChildItem requirements/*.txt | Get-Content | Out-File requirements.txt
      displayName: Coalesce requirements files

    - task: ComponentGovernanceComponentDetection@0
      inputs:
        verbosity: Verbose
        alertWarningLevel: Medium
        failOnAlert: true
      displayName: Component Governance ( aka.ms/cgdocs )

    - task: notice@0
      displayName: generate NOTICE
      inputs:
        outputformat: text
