trigger:
  batch: true
  branches:
    include:
    - main

schedules:
- cron: 0 12 * * 0
  displayName: weekly Sunday build
  branches:
    include:
    - main
  always: true


pool:
  vmImage: ubuntu-latest

steps:

- checkout: self
  clean: true

- bash: |
    cat requirements/requirements-logging.txt >> requirements.txt
    cat requirements/requirements-pipeline.txt >> requirements.txt
    cat requirements/requirements-build.txt >> requirements.txt
    cat requirements/requirements-dev.txt >> requirements.txt  
  displayName: Pool Requirement Files

- task: ComponentGovernanceComponentDetection@0
  inputs:
    verbosity: Verbose
    alertWarningLevel: Medium
    failOnAlert: true
  displayName: Component Governance ( aka.ms/cgdocs )

- task: notice@0
  displayName: generate NOTICE
  inputs:
    outputformat: text

# https://aka.ms/bandit/
- task: Bandit@1
  inputs:
    targetsType: banditPattern
    targetsBandit: $(Build.SourcesDirectory)
    targetsBanditRecursive: true
    ruleset: none
    policyName: M365
    minSeverity: Low
    minConfidence: low
    baseline:
  condition: succeededOrFailed()
