trigger:
  batch: true
  branches:
    include:
    - main

pr:
- main

schedules:
- cron: 0 12 * * 0
  displayName: weekly Sunday build
  branches:
    include:
    - main
  always: true

parameters:

- name: images
  type: object
  default:
  - ubuntu-latest
  # Dependencies and the corresponding CG alerts may be different
  # in each operating system.
  - windows-latest

jobs:

- ${{ each image in parameters.images }}:

  - job: ${{ image }}

    pool:
      vmImage: ${{ image }}

    steps:

    - checkout: self
      clean: true

    - pwsh: |
        Get-ChildItem requirements/*.txt | Get-Content | Out-File requirements.txt
      displayName: Coalesce requirements files

    - task: ComponentGovernanceComponentDetection@0
      inputs:
        verbosity: Verbose
        alertWarningLevel: Medium
        failOnAlert: true
      displayName: Component Governance ( aka.ms/cgdocs )

  - task: notice@0
    displayName: generate NOTICE
    inputs:
      outputformat: text
